language: python

python:
  - 2.6
  - 2.7
  - 3.3

env:
  - DJANGO=Django==1.4 --use-mirrors
  - DJANGO=Django==1.5 --use-mirrors
  - DJANGO=Django==1.6 --use-mirrors

install:
  - pip install -q $DJANGO
  - pip install -e . --use-mirrors

script:
  - python setup.py test
